import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import { useAuth } from "../hooks/useAuth";

export default function PastoralCasesCard({ teenId }: { teenId: any }) {
  const { token, user } = useAuth(); const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [show, setShow] = useState(false);
  const cases = useQuery(api.pastoralCases.listByTeen, token ? { token, teenId } : "skip") ?? []; const create = useMutation(api.pastoralCases.create); const addNote = useMutation(api.pastoralCases.addAction); const change = useMutation(api.pastoralCases.updateStatus); const reassign = useMutation(api.pastoralCases.reassign); const assignable = useQuery(api.pastoralTasks.listAssignableUsers, token ? { token } : "skip") ?? [];
  const role = (user as any)?.role; const supervisor = ["admin", "pastor", "director", "coordinador"].includes(role);
  return <section className="bg-card rounded-card shadow-soft p-5 space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-display font-semibold text-base">Expedientes pastorales sensibles</h2><p className="text-xs text-ink/50 mt-1">Acceso restringido y trazable. La IA solo puede sugerir cuidado.</p></div>{supervisor && <button onClick={() => setShow(!show)} className="rounded-lg bg-primary-600 px-3 py-2 text-xs font-semibold text-white">Abrir caso</button>}</div>
    {show && <div className="rounded-xl border border-primary-100 bg-primary-50/50 p-3 space-y-2"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título neutral del caso" className="w-full rounded-lg border border-ink/10 p-2 text-sm"/><button onClick={async()=>{if(token&&title.trim()){await create({token,teenId,title,priority:"medium"});setTitle("");setShow(false)}}} className="rounded-lg bg-primary-700 px-3 py-2 text-xs font-semibold text-white">Crear expediente</button></div>}
    {cases.map((item:any)=><div key={item._id} className="rounded-xl border border-ink/10 p-3 text-sm"><div className="flex justify-between gap-2"><strong>{item.title}</strong><span className="capitalize text-xs">{item.status.replace("_"," ")}</span></div>{supervisor&&<select value={item.assignedToUserId || ""} onChange={(e)=>token&&reassign({token,caseId:item._id,assignedToUserId:(e.target.value || undefined) as any,notes:"Responsable actualizado desde ficha."})} className="mt-2 w-full rounded-lg border border-ink/10 px-2 py-1.5 text-xs"><option value="">Sin responsable asignado</option>{assignable.map((person:any)=><option key={person._id} value={person._id}>{person.name}</option>)}</select>}<div className="mt-2 flex flex-wrap gap-2"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Registrar nota" className="min-w-0 flex-1 rounded-lg border border-ink/10 px-2 py-1.5 text-xs"/><button onClick={async()=>{if(token&&note.trim()){await addNote({token,caseId:item._id,notes:note});setNote("")}}} className="rounded-lg border border-ink/10 px-2 py-1 text-xs">Nota</button>{supervisor&&<button onClick={()=>token&&change({token,caseId:item._id,status:"referred",notes:"Caso derivado para seguimiento."})} className="rounded-lg border border-ink/10 px-2 py-1 text-xs">Derivar</button>}{supervisor&&<button onClick={()=>token&&change({token,caseId:item._id,status:"review_pending",notes:"Revisión registrada."})} className="rounded-lg border border-ink/10 px-2 py-1 text-xs">Revisar</button>}{supervisor&&<button onClick={()=>token&&change({token,caseId:item._id,status:"closed",notes:"Cierre registrado."})} className="rounded-lg border border-ink/10 px-2 py-1 text-xs">Cerrar</button>}</div></div>)}
    {!cases.length && <p className="text-sm text-ink/45">No hay expedientes visibles para este adolescente.</p>}</section>;
}
